# Generated by Django 3.2.12 on 2025-05-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos/'),
        ),
    ]
