# Generated by Django 3.2.12 on 2025-05-25 06:55

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_group_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=chats.models.user_file_path),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=chats.models.group_file_path),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
